### ISSUE TITLE
[Question] How to transform/override the data model name?

### ISSUE THREAD

**Issue by 0xFustang** [SigmaHQ/pySigma-backend-splunk#26]
Hi! I am not sure if this is the right place to ask questions about the pipelines, please apologies if this is not the right place.

I am trying to convert rules related to process_creation into Splunk CIM data model (using Endpoint.Processes). In my context, the default data model Endpoint.Processes was copied into Endpoint.Foo to avoid using the default one when it gets updated.

The question is, how can I change/override the data model name in the conversion? Should I use transformations configuration file?

My test:

Rule: https://raw.githubusercontent.com/SigmaHQ/sigma/master/rules/windows/process_creation/proc_creation_win_bitsadmin_download_susp_extensions.yml

Commands:

```
$ sigma convert \
    --target splunk \
    --pipeline splunk_cim \
    ./proc_creation_win_bitsadmin_download_susp_extensions.yml
Parsing Sigma rules  [####################################]  100%
Processes.process_path="*\\bitsadmin.exe" OR Processes.original_file_name="bitsadmin.exe" Processes.process IN ("* /transfer *", "* /create *", "* /addfile *") Processes.process IN ("*.7z*", "*.asax*", "*.ashx*", "*.asmx*", "*.asp*", "*.aspx*", "*.bat*", "*.cfm*", "*.cgi*", "*.chm*", "*.cmd*", "*.dll*", "*.gif*", "*.jpeg*", "*.jpg*", "*.jsp*", "*.jspx*", "*.log*", "*.png*", "*.ps1*", "*.psm1*", "*.rar*", "*.scf*", "*.sct*", "*.txt*", "*.vbe*", "*.vbs*", "*.war*", "*.wsf*", "*.wsh*", "*.xll*", "*.zip*")
```

I would like to have: 

```
Foo.process_path="*\\bitsadmin.exe" OR Foo.original_file_name="bitsadmin.exe" Foo.process IN ("* /transfer *", "* /create *", "* /addfile *") Foo.process ...
```

**Comment by thomaspatzke** [comment]
That's the right place for your question 😉

The data model name is defined by the `data_model_set` processing state variable that can be set with the [`set_state` transformation](https://sigmahq-pysigma.readthedocs.io/en/latest/Processing_Pipelines.html#sigma.processing.transformations.SetStateTransformation) in a YAML processing pipeline definition that replaces the existing data model processing pipeline used on your command [similar to the pipeline built-in in the Splunk backend](https://github.com/SigmaHQ/pySigma-backend-splunk/blob/13cf0c4b550e6a70fae218a7af6d98c7c4ec8564/sigma/pipelines/splunk/splunk.py#L133). The [pipeline YAML](https://sigmahq-pysigma.readthedocs.io/en/latest/Processing_Pipelines.html#specifying-processing-pipelines-as-yaml) must be somewhat like:

```yaml
name: Custom data models
priority: 100
transformations:
- id: custom_process_dm
  type: set_state
  key: data_model_set
  value: Endpoint.Foo
  rule_conditions:
  - type: logsource
    category: process_creation
- id: custom_process_mapping
  type: field_name_mapping
  mapping:
    ImageFileName: Foo.process_path
    ...
  rule_conditions:
  - type: logsource
    category: process_creation
```

**Comment by 0xFustang** [comment]
Thank you very much @thomaspatzke. 

I modified my pipeline YAML into:

```yaml
name: Custom data models
priority: 100
transformations:
  - id: custom_process_dm
    type: set_state
    key: data_model_set
    val: 'Endpoint.Foo'
    rule_conditions:
      - type: logsource
        category: process_creation
  - id: custom_process_mapping
    type: field_name_mapping
    mapping:
      OriginalFileName: Foo.original_file_name
      Image: Foo.process_path
      CommandLine: Foo.process
    rule_conditions:
      - type: logsource
        category: process_creation
```

And I get the following result:

```bash
$ sigma convert --target splunk -p custom_data_model.yml ./proc_creation_win_bitsadmin_download_susp_extensions.yml
Parsing Sigma rules  [####################################]  100%
Foo.process_path="*\\bitsadmin.exe" OR Foo.original_file_name="bitsadmin.exe" Foo.process IN ("* /transfer *", "* /create *", "* /addfile *") Foo.process IN ("*.7z*", "*.asax*", "*.ashx*", "*.asmx*", "*.asp*", "*.aspx*", "*.bat*", "*.cfm*", "*.cgi*", "*.chm*", "*.cmd*", "*.dll*", "*.gif*", "*.jpeg*", "*.jpg*", "*.jsp*", "*.jspx*", "*.log*", "*.png*", "*.ps1*", "*.psm1*", "*.rar*", "*.scf*", "*.sct*", "*.txt*", "*.vbe*", "*.vbs*", "*.war*", "*.wsf*", "*.wsh*", "*.xll*", "*.zip*") | table Foo.original_file_name,Foo.process_path,Foo.process
```

However, I am not able to use the `data_model` splunk format, I get the following output:

```
sigma convert --target splunk -f data_model -p custom_data_model.yml ./proc_creation_win_bitsadmin_download_susp_extensions.yml
Parsing Sigma rules  [####################################]  100%
Error while conversion: No fields specified by processing pipeline
```

Should I add another condition in my pipeline YAML?
