### ISSUE TITLE
"aliases" attribute in sigma correlation rules not translated

### ISSUE THREAD

**Issue by sec-hbaer** [SigmaHQ/pySigma-backend-splunk#45]
Hi, 
I am working on a larger Sigma correlation rule. As part of that rule, I want to use the "aliases" attribute to create a shared name for fields form different logsources.
While converting the correlation rule with the Splunk backend, the resulting rule does not seem to have considered the alias (as far as I can read splunk queries).

I've stripped down my rule to following MVP:  
```
title: MVP Sigma conversion test with aliases
id: 192c842d-a934-44a7-aeea-3e72bba6291f
status: experimental
description: minimum sigma rule to show conversion of "aliases" with Splunk backend
author: Herbert Bärschneider @SEC Consult
date: 2024-10-17
correlation:
    type: event_count
    rules:
        - 2a239bba-583c-4afc-a1f7-6736e8e9e5b0 # user remote logon
    aliases:
        targeted_useraccount:
            logon_remote: TargetUserName
    group-by:
        - targeted_useraccount
    timespan: 5m
    condition:
        gte: 100
level: medium
---
title: User Remote Logon
id: 2a239bba-583c-4afc-a1f7-6736e8e9e5b0
status: test
description: Detect remote login
author: Herbert Bärschneider @SEC Consult
date: 2024-10-08
name: logon_remote
logsource:
    product: windows
    service: security
detection:
    selection:
        EventID: 4624
        LogonType: 10
    condition: selection
fields:
    - TargetUserName
    - IpAddress # where the connection came from
falsepositives:
    - Legitimate remote desktop activity.
level: informational
```

When running the command `sigma convert -t splunk -p splunk_windows mvp.yml`, I get following output:
```
source="WinEventLog:Security" EventCode=4624 LogonType=10 | table TargetUserName,IpAddress

| bin _time span=5m
| stats count as event_count by _time targeted_useraccount

| search event_count >= 100
```

The alias name is used in the query, but it is seemingly not connected with the event fields.

I am unsure, if this problem comes from the backend or an error on my side. I would appreciate feedback.

Kind Regards

Herbert

**Comment by thomaspatzke** [comment]
Hi Herbert! This works as intended. The correlation alias feature is intended for defining common names for correlating fields from *different* event types. This means that the alias definition for a field refers at least two or more different Sigma rules. In your correlation, only one Sigma rule is referred and therefore it is not the intended use case for aliasing. For these rules the Splunk backend [doesn't generates the normalization expressions](https://github.com/SigmaHQ/pySigma-backend-splunk/blob/15218df8dd91c689966c3a3297ec6c7f4147d27f/sigma/backends/splunk/splunk.py#L181).

**Comment by sec-hbaer** [comment]
@thomaspatzke even when using mutliple sigma rules, it still does not seem to work.

Following is the actual Sigma correlation rule I am trying to make work:
```
title: Usage of RDP from single source to multiple destinations
id: b0863b33-d750-413e-83ae-b0afdbac3a75
status: experimental
description: Stacks RDP usage by user account over a defined timeframe, looking for situations, where one user connects to multiple different targets over RDP
author: Herbert Bärschneider @SEC Consult
date: 2024-10-08
correlation:
    type: event_count
    rules: # use one of the rules to identify remote connections on a system
        - 118276ab-7af4-4158-92d7-c4feae836717 # user remote logon
        - 160fd7be-b1ef-429b-8695-4295898dd59b # RDP connection detected on target via session logon
        - fd11a311-8185-4cf6-9502-71e594c186aa # RDP connection detected on target via user authentication
    aliases:
        targeted_useraccount:
            logon_remote: TargetUserName
            rdp_session_logon: User
            rds_user_authentication: Param1
    group-by:
        - targeted_useraccount
    timespan: 24h # needs to be adjusted based on practical experience!
    condition:
        gte: 10 # needs to be adjusted based on practical experience!
level: medium
---
title: User Remote Logon
id: 118276ab-7af4-4158-92d7-c4feae836717
status: test
description: Detect remote login
author: Herbert Bärschneider @SEC Consult
date: 2024-10-08
name: logon_remote
logsource:
    product: windows
    service: security
detection:
    selection:
        EventID: 4624
        LogonType: 10
    condition: selection
fields:
    - TargetUserName
    - IpAddress # where the connection came from
falsepositives:
    - Legitimate remote desktop activity.
level: informational
---
title: Session logon for Remote Desktop Services
id: 160fd7be-b1ef-429b-8695-4295898dd59b
status: test
description: Detects a RDP connection to the system
author: Herbert Bärschneider @SEC Consult
date: 2024-10-08
name: rdp_session_logon
logsource:
    product: windows
    service: terminalservices-localsessionmanager
detection:
    selection:
        EventID: 21
    condition: selection
fields:
    - User # field contains username and domain
    - Address # where the connection came from
falsepositives:
    - Legitimate remote desktop activity.
level: informational
---
title: User authentication for Remote Desktop Services
id: fd11a311-8185-4cf6-9502-71e594c186aa
status: test
description: Detects user authentication for a RDP connection to the system
author: Herbert Bärschneider @SEC Consult
date: 2024-10-08
name: rds_user_authentication
logsource:
    product: windows
    service: terminalservices-remoteconnectionmanager
detection:
    selection:
        EventID: 1149
    condition: selection
fields:
    - Param1 # field contains the username (without domain info)
    - Param2 # system name where the connection came from
    - Param3 # address where the connection came from
falsepositives:
    - Legitimate remote desktop activity.
level: informational
```

when running `sigma convert -t splunk -p splunk_windows correlation_win_lateral-movement_sus_rdp_usage.yml`, I get following output:
```
| multisearch
[ search source="WinEventLog:Security" EventCode=4624 LogonType=10 | table TargetUserName,IpAddress | eval event_type="logon_remote" ]
[ search source="WinEventLog:Microsoft-Windows-TerminalServices-LocalSessionManager/Operational" EventCode=21 | table User,Address | eval event_type="rdp_session_logon" ]
[ search EventCode=1149 | table Param1,Param2,Param3 | eval event_type="rds_user_authentication" ]

| bin _time span=24h
| stats count as event_count by _time targeted_useraccount

| search event_count >= 10
```

Im not familiar with the Splunk query language, but I still see no matching of the search results to the alias "targeted_useraccount"
