### ISSUE TITLE
index missing in correlation rules' subsearches

### ISSUE THREAD

**Issue by arblade** [SigmaHQ/pySigma-backend-splunk#50]
I recently encountered an issue with some correlation rules in the splunk backend.
Some correlation rules are translated into multiple subsearches like for instance, for a temporal one with multiple subrules : 

```yaml
<first_rule>
---
<second_rule>
---
title: correlation rule example
correlation:
    type: temporal
    rules:
         - first_rule
         - second_rule
    group-by:
         - Hostname
    timespean: 1m
...

```
could give something like :
```spl
| multisearch
[search EventID=10 ...]
[search EventID=10 ...]

| bin ...
| stats ...

| search event_type_count>=2
```

The thing is, the "subsearches" (understand the `[search ...]` parts in the example above), need an index to work, like `[search index=* ...]`.
I was previously using a postprocessing in my pipeline to insert it via a template : 
```yaml
postprocessing:
    - id: index in subsearches
      template: |+
          index={{rule.custom_attributes["index"]}} {{query}}
      rule_cond_not: true
      rule_conditions:
          - type: is_sigma_correlation_rule
```
But now, since a few months, as our pysigma got updated, the [exclusion of correlation rules' subrules from postprocessing](https://github.com/SigmaHQ/pySigma/blob/03dcaacf942e80f9df41973257423a20257a097e/sigma/conversion/base.py#L214) broke our conversion, resulting in `[search EventID=10 ...]` instead of `[search index=* EventID=10]`.

I did not find a way to make it work with the current pysigma and splunk backend version, any idea ?
If not, I am willing to work on a PR for this.
